############# English navigation ##############

# main menu
[[main]]
name = "About"
weight = 1

[[main]]
parent = "About"
name = "Founders"
pageRef = "/founders"

[[main]]
parent = "About"
name = "Members"
pageRef = "/members"

[[main]]
name = "How We Invest"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Resources"
weight = 3

[[main]]
parent = "Resources"
name = "Blog"
pageRef = "/resources/blog"

[[main]]
parent = "Resources"
name = "Knowledge Base"
pageRef = "/resources/knowledge-base"

[[main]]
parent = "Resources"
name = "Investor Deck"
url = "https://slides.gluon.vc/investor-deck"

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Terms of Service"
pageRef = "/terms-of-service"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
