############# English navigation ##############

# main menu

[[main]]
name = "Investors"
weight = 1

[[main]]
parent = "Investors"
name = "Founders"
pageRef = "/founders"
weight = 1

[[main]]
parent = "Investors"
name = "Investor Deck"
url = "https://slides.gluon.vc/investor-deck"
weight = 2

[[main]]
parent = "Investors"
name = "Join Us"
pageRef = "/membership"
weight = 3

[[main]]
name = "How We Invest"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Knowledge Base"
url = "https://kb.gluon.vc/"
weight = 3

# footer menu

[[footer]]
name = "Terms of Service"
url = "https://kb.gluon.vc/terms-of-service"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "https://kb.gluon.vc/privacy-policy"
weight = 2
