############# Czech navigation ##############

# main menu

[[main]]
name = "Investoři"
weight = 1

[[main]]
parent = "Investoři"
name = "Zakladatelé syndikátu"
pageRef = "/founders"
weight = 1

[[main]]
parent = "Investoři"
name = "Prezentace pro investory"
url = "https://slides.gluon.vc/investor-deck"
weight = 2

[[main]]
parent = "Investoři"
name = "Přidejte se"
pageRef = "/membership"
weight = 3

[[main]]
name = "Jak investujeme"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Znalostní báze (EN)"
url = "https://kb.gluon.vc/"
weight = 3

# footer menu

[[footer]]
name = "Všeobecné obchodní podmínky"
url = "https://kb.gluon.vc/terms-of-service"
weight = 1

[[footer]]
name = "Zásady ochrany osobních údajů"
url = "https://kb.gluon.vc/privacy-policy"
weight = 2