############# English navigation ##############

# main menu

[[main]]
name = "Investori"
weight = 1

[[main]]
parent = "Investori"
name = "Zakladatelia syndikátu"
pageRef = "/founders"
weight = 1

[[main]]
parent = "Investori"
name = "Prezentácia pre investorov"
url = "https://slides.gluon.vc/investor-deck"
weight = 2

[[main]]
parent = "Investori"
name = "Pridajte sa"
pageRef = "/membership"
weight = 3

[[main]]
name = "Ako investujeme"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Zdroje"
weight = 3

[[main]]
parent = "Zdroje"
name = "Wiki"
pageRef = "/resources/knowledge-base"
weight = 1

[[main]]
parent = "Zdroje"
name = "Blog"
pageRef = "/resources/blog"
weight = 2

# footer menu

[[footer]]
name = "Všeobecné pbchodné podmienky"
pageRef = "/resources/terms-of-service"
weight = 1

[[footer]]
name = "Zásady ochrany osobných údajov"
pageRef = "/resources/privacy-policy"
weight = 2
