############# English navigation ##############

# main menu

[[main]]
name = "Investori"
weight = 1

[[main]]
parent = "Investori"
name = "Zakladatelia syndikátu"
pageRef = "/founders"
weight = 1

[[main]]
parent = "Investori"
name = "Prezentácia pre investorov"
url = "https://slides.gluon.vc/investor-deck"
weight = 2

[[main]]
parent = "Investori"
name = "Pridajte sa"
pageRef = "/membership"
weight = 3

[[main]]
name = "Jak investujeme"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Znalostná báza (EN)"
url = "https://kb.gluon.vc/"
weight = 3

# footer menu

[[footer]]
name = "Všeobecné pbchodné podmienky"
url = "https://kb.gluon.vc/terms-of-service"
weight = 1

[[footer]]
name = "Zásady ochrany osobných údajov"
url = "https://kb.gluon.vc/privacy-policy"
weight = 2
