############# English navigation ##############

# main menu

[[main]]
name = "Investors"
weight = 1

# [[main]]
# parent = "Investors"
# name = "Founders"
# pageRef = "/founders"
# weight = 1

[[main]]
parent = "Investors"
name = "Investor Deck"
url = "https://slides.gluon.vc/investor-deck"
weight = 2

[[main]]
parent = "Investors"
name = "Join Us"
pageRef = "/membership"
weight = 3

[[main]]
name = "How We Invest"
pageRef = "/how-we-invest"
weight = 2

[[main]]
name = "Resources"
weight = 3

[[main]]
parent = "Resources"
name = "Knowledge Base"
pageRef = "/resources/knowledge-base"
weight = 1

[[main]]
parent = "Resources"
name = "Blog"
pageRef = "/resources/blog"
weight = 2

# footer menu

[[footer]]
name = "Terms of Service"
pageRef = "/resources/terms-of-service"
weight = 1

[[footer]]
name = "Privacy Policy"
pageRef = "/resources/privacy-policy"
weight = 2
